name: Build Wails App (Cross-platform)

on:
  push:
    tags:
      - '*'  
env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: "Pomodoro+"
            platform: "linux/amd64"
            os: "ubuntu-latest"
          - name: "Pomodoro+"
            platform: "windows/amd64"
            os: "windows-latest"

    runs-on: ${{ matrix.build.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Wails app
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false  
          go-version: '1.22'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build.name }}-${{ matrix.build.platform }}
          path: |
            ./build
